name: test matrix

on:
  workflow_dispatch:
  
jobs:
  lava-result:
    runs-on: 'ubuntu-latest'
    strategy:
      max-parallel: 1
      matrix:
        wait: [1,2,3,4,5,6,7,8,9,10]
    steps:
      - name: run ${{ matrix.wait }}
        id: result-wait
        if: ${{ steps.result-wait.outputs.is_ok != 'ok' }}
        run: |
          
          echo ${{ matrix.wait }}
          if [ "${{ matrix.wait }}" = "2" ]; then
            echo "is_ok=ok" >> $GITHUB_OUTPUT
            exit 0
          fi
          max_time_seconds=$((2))
          for((i=1; i<=max_time_seconds; i++)); do
              echo "================${i}==================="
              ip addr
              echo "======================================="
              sleep 5
          done
          
