name: test matrix

on:
  workflow_dispatch:
  
jobs:
  lava-result:
    runs-on: 'ubuntu-latest'
    strategy:
      max-parallel: 1
      matrix:
        wait: [1,2,3,4,5,6,7,8,9,10]
    steps:
      - run: |
          echo ${{ matrix.wait }}
          for((i=1; i<=${{matrix.wait}}; i++)); do
              echo $i
              sleep 5
          done
