name: test matrix

on:
  workflow_dispatch:
  
jobs:
  lava-result:
    runs-on: 'ubuntu-latest'
    strategy:
      max-parallel: 1
      matrix:
        wait: [1,2,3,4,5,6,7,8,9,10]
    steps:
      - name: run ${{ matrix.wait }}
        if: ${{ !env.lava_result }}
        run: |
          ip addr
          echo ${{ matrix.wait }}
          for((i=1; i<=${{matrix.wait}}; i++)); do
              echo $i/${{ matrix.wait }}
              sleep 5
          done
          if [ "${{ matrix.wait }}" = 5 ]; then
              echo "lava_result=over" >> $GITHUB_ENV
          fi
