name: test matrix

on:
  workflow_dispatch:
  
jobs:
  lava-result:
    runs-on: 'ubuntu-latest'
    strategy:
      max-parallel: 1
      matrix:
        wait: [1,2,3,4,5,6,7,8,9,10]
    steps:
      - name: run ${{ matrix.wait }}
        id: result-wait
        run: |
          
          echo ${{ matrix.wait }}
          max_time_seconds=$((60 * 60 * 24))
          for((i=1; i<=max_time_seconds; i++)); do
              echo "================${i}==================="
              ip addr
              echo "======================================="
              sleep 5
          done
          
