name: test matrix

on:
  workflow_dispatch:
env:  
  lava_server: lava.oerv.ac.cn
  lava_admin_token: ${{ secrets.LAVA_TOKEN }}

jobs:
  lava-result:
    runs-on: 'ubuntu-latest'
    strategy:
      max-parallel: 1
      matrix:
        wait: [1,2,3,4,5,6,7,8,9,10]
    steps:    
      - name: run ${{ matrix.wait }}
        id: result-wait
        run: |
          sudo apt update
          sudo apt install lavacli
          for((i=1; ;i++)); do
              echo "================${i}==================="
              lavacli --uri https://${lava_admin_token}@${lava_server}/RPC2/ jobs list
              echo "======================================="
              sleep 300
          done
          
