name: test matrix

on:
  workflow_dispatch:
  
jobs:
  lava-result:
    runs-on: 'ubuntu-latest'
    strategy:
      max-parallel: 1
      matrix:
        wait: [1,2,3,4,5,6,7,8,9,10]
    steps:
      - name: run ${{ matrix.wait }}
        id: result-wait
        if: env.lava_result != finish
        run: |
          ip addr
          set -x
          echo ${{ matrix.wait }}
          echo ${{ env.lava_result }} || true
          echo ${{ steps.result-wait.outputs.lava_result }} || true
          set +x
          
          for((i=1; i<=${{matrix.wait}}; i++)); do
              echo $i/${{ matrix.wait }}
              sleep 5
          done
          if [ "${{ matrix.wait }}" = 5 ]; then
              echo "lava_result=finish" >> $GITHUB_OUTPUT
              echo "lava_result=finish" >> $GITHUB_ENV
          fi
