name: RVCK CI

on:
  workflow_call:
    inputs:
      WORKFLOW_REF:
        required: false
        type: string
        default: main

jobs:
  # kernel-check:
  #   runs-on: 'action-runner-9950x-196.2'
  #   container:
  #     image: 'hub.oepkgs.net/oerv-ci/rava-action-runner:latest'
  #   env:
  #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         repository: 'OERV-RVCI/RAVA-action'
  #         ref: ${{ inputs.WORKFLOW_REF }}
      
  #     - id: parse-request
  #       uses: ./parse-request
   
  #     - name: checkout kernel source
  #       run: |
  #         rm -rf kernel-src || true
  #         mkdir -p kernel-src && (cd kernel-src && bash ../src/git-fetch-in-dir.sh "${{ steps.parse-request.outputs.FETCH_REF }}")
  #       env:
  #         REPO: ${{ steps.parse-request.outputs.REPO }}
  #         GIT_FETCH_DEPTH: 1
      
  #     - uses: ./kernel-check/kunit-test
  #       with:
  #         kernel-src-dir: kernel-src

  #     - uses: ./kernel-check/kernel-build
  #       id: kernel-build
  #       with:
  #         kernel-src-dir: kernel-src
  #         sshkey_content: ${{ secrets.KERNEL_DOWNLOAD_SERVER_SSHKEY }}
      
  #     - uses: ./kernel-check/lava-trigger
  #       with:
  #         lava_token: ${{ secrets.LAVA_TOKEN }}

       
  parse-request:
    permissions:
      issues: write
      pull-requests: write
    uses: OERV-RVCI/RVCK-pipeline/.github/workflows/parse-request.yml@actions
    with:
      WORKFLOW_REPO: OERV-RVCI/RVCK-pipeline
      WORKFLOW_REF: actions
  
  kunit-test:
    needs: [parse-request]
    permissions:
      issues: write
      pull-requests: write
    uses: OERV-RVCI/RVCK-pipeline/.github/workflows/kunit-test.yml@actions
    secrets: inherit
    with:
      WORKFLOW_REPO: OERV-RVCI/RVCK-pipeline
      WORKFLOW_REF: actions
      kernel_src_repo: ${{ needs.parse-request.outputs.REPO }}
      fetch_ref: ${{ needs.parse-request.outputs.FETCH_REF }}
      issue_id: ${{ needs.parse-request.outputs.ISSUE_ID }}
  
  kernel-build:
    needs: [parse-request]
    uses: OERV-RVCI/RVCK-pipeline/.github/workflows/kernel-build.yml@actions
    permissions:
      issues: write
      pull-requests: write
    secrets:
      sshkey_content: ${{ secrets.KERNEL_DOWNLOAD_SERVER_SSHKEY }}
    with:
      WORKFLOW_REPO: OERV-RVCI/RVCK-pipeline
      WORKFLOW_REF: actions
      kernel_src_repo: ${{ needs.parse-request.outputs.REPO }}
      fetch_ref: ${{ needs.parse-request.outputs.FETCH_REF }}
      issue_id: ${{ needs.parse-request.outputs.ISSUE_ID }}
      
  lava-trigger:
    needs: [parse-request, kernel-build]
    uses: OERV-RVCI/RVCK-pipeline/.github/workflows/lava-trigger.yml@actions
    permissions:
      issues: write
      pull-requests: write
    secrets: 
      lava_token: ${{ secrets.LAVA_TOKEN }}
    with:
      WORKFLOW_REPO: OERV-RVCI/RVCK-pipeline
      WORKFLOW_REF: actions
      REPO: ${{ needs.parse-request.outputs.REPO }}
      ISSUE_ID: ${{ needs.parse-request.outputs.ISSUE_ID }}
      kernel_download_url: ${{ needs.kernel-build.outputs.kernel_download_url }}
      testcase_repo: ${{ needs.parse-request.outputs.testcase_repo }}
      lava_template: ${{ needs.parse-request.outputs.lava_template }}
      testcase_url: ${{ needs.parse-request.outputs.testcase_url }}

  check-patch:
    needs: [parse-request]
    if: ${{ needs.parse-request.outputs.SRC_REF }}
    permissions:
      issues: write
      pull-requests: write
    uses: OERV-RVCI/RVCK-pipeline/.github/workflows/check-patch.yml@actions
    secrets: inherit
    with:
      WORKFLOW_REPO: OERV-RVCI/RVCK-pipeline
      WORKFLOW_REF: actions
      kernel_src_repo: ${{ needs.parse-request.outputs.REPO }}
      fetch_ref: ${{ needs.parse-request.outputs.FETCH_REF }}
      src_ref: ${{ needs.parse-request.outputs.SRC_REF }}
      issue_id: ${{ needs.parse-request.outputs.ISSUE_ID }}
